# Created by trellis-cli v1.11.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  shadynasty.online:
    site_hosts:
    - canonical: stage.shadynasty.online
    local_path: ../site
    branch: main
    repo: git@github.com:david-muirhead/shadystage.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
